CREATE TABLE Flight (
FLIGHTNUMBER INT (8) NOT NULL,
TOCITY VARCHAR(30) NOT NULL,
FROMCITY VARCHAR(30) NOT NULL,
DEPARTURETIME DATETIME NOT NULL,
ARRIVALTIME DATETIME NOT NULL,
PASSENGERS INT(10),
PRIMARY KEY (FLIGHTNUMBER)
);

DROP TABLE User;

CREATE TABLE User (
EMAIL VARCHAR(100) NOT NULL,
FIRSTNAME VARCHAR(25) NOT NULL,
LASTNAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
ZIP INT(5) NOT NULL,
STATE VARCHAR(20) NOT NULL,
PASSWORD VARCHAR (25) NOT NULL,
SSN INT(9) NOT NULL,
SECQ VARCHAR(100) NOT NULL,
SECQANSWER VARCHAR(100) NOT NULL,
ISADMIN BOOLEAN NOT NULL,
PRIMARY KEY (EMAIL)
);

CREATE TABLE UserFlight (
FLIGHTNUMBER       INT(8) NOT NULL,
USEREMAIL       VARCHAR(100) NOT NULL,
PRIMARY KEY (FLIGHTNUMBER, USEREMAIL),
FOREIGN KEY (FLIGHTNUMBER) REFERENCES Flight(FLIGHTNUMBER),
FOREIGN KEY (USEREMAIL) REFERENCES User(EMAIL)
);       

